apiVersion: v1
kind: ConfigMap
metadata:
  name: shield-backend-config
  namespace: shield
data:
  # Environment variables for the application
  PYTHONDONTWRITEBYTECODE: "1"
  PYTHONUNBUFFERED: "1"
  # Add any other environment variables your application needs
  # DATABASE_URL: "mongodb://mongo-service:27017/shield"
  # LOG_LEVEL: "info"
