name: Lint Python with Ruff

on:
  pull_request:
    paths:
      - "**.py"
      - "requirements.txt"
      - "dev-requirements.txt"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dev-requirements
        run: pip install -r dev-requirements.txt
      - name: Run Ruff
        run: ruff check .
